# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "ubuntu/wily64"
  config.vm.box_check_update = false
  config.ssh.insert_key = false
  config.vm.network "private_network", ip: "192.168.33.15"
  config.vm.synced_folder "../", "/etc/puppet/modules/"

  config.vm.define "CentOS_7_test" do |centos7|
  	centos7.vm.box = "puppetlabs/centos-7.0-64-puppet"
  	centos7.vm.box_version = "1.0.1"
  	centos7.vm.box_check_update = false
  end

  config.vm.define "CentOS_6_test" do |centos6|
  	centos6.vm.box = "puppetlabs/centos-6.6-64-puppet"
  	centos6.vm.box_version = "1.0.1"
  	centos6.vm.box_check_update = false
  end

  config.vm.define "Ubuntu_15_test" do |ubuntu|
    ubuntu.vm.box = "ubuntu/wily64"
    ubuntu.vm.box_check_update = false
  end

  config.vm.define "Ubuntu_16_test" do |ubuntu|
    ubuntu.ssh.private_key_path = "~/.vagrant.d/20170926_vagrant_private_key"
    ubuntu.vm.network "private_network", ip: "192.168.33.26"
    ubuntu.vm.box = "reclusive/xenial64-puppet"
    ubuntu.vm.box_check_update = true
  end
end
