# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  config.vm.box_check_update = false
  config.ssh.insert_key = false
  config.vm.hostname = "vagrant.vm"

  config.vm.synced_folder "../", 	"/etc/puppet/modules"
  
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end
  
  config.vm.define "CentOS_7_test" do |centos7|
  	centos7.vm.box = "puppetlabs/centos-7.0-64-puppet"
  	centos7.vm.box_version = "1.0.1"
  	centos7.vm.box_check_update = false
    centos7.vm.network "private_network", ip: "192.168.33.17", auto_config: true
  end

  config.vm.define "CentOS_6_test" do |centos6|
  	centos6.vm.box = "puppetlabs/centos-6.6-64-puppet"
  	centos6.vm.box_version = "1.0.1"
  	centos6.vm.box_check_update = false
    centos6.vm.network "private_network", ip: "192.168.33.16", auto_config: true
  end

  config.vm.define "Ubuntu_15_test" do |ubuntu|
    ubuntu.vm.box = "ubuntu/wily64"
    ubuntu.vm.box_check_update = false
    config.vm.network "private_network", ip: "192.168.33.15", auto_config: true
    ubuntu.ssh.private_key_path = ["C:/Users/Alexander/.vagrant.d/20170926_vagrant_private_key","C:/Users/Alexander/.vagrant.d/insecure_private_key"]
  end
end
