# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
    
  config.vm.synced_folder "../", "/etc/puppet/modules"
  config.ssh.insert_key = false
  #Getting the error:Cannot allocate memory - fork(2)
  #Ruby needs more headroom to fork processes as it copies the entire parent context before collapsing it down.
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "5122"
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  end
  config.vm.define "dev" do |dev|
    dev.vm.hostname = "jenkins-dev"
    dev.vm.network "private_network", ip: "192.168.33.16"
    dev.vm.box = "ubuntu/wily64"
  	dev.vm.synced_folder "../", "/etc/puppet/modules"
    dev.vm.synced_folder "~/Dropbox/Projects/Jenkins", "/vagrant/backups/"
	  dev.vm.provision "puppet" do |puppet|
 		  puppet.manifests_path = "manifests"
		  puppet.manifest_file  = "jenkins.pp"
    end
    dev.vm.provider "virtualbox" do |v|
      v.memory = 2048
    end
  end

  config.vm.define "CentOS_7_test" do |centos7|
  	centos7.vm.box = "puppetlabs/centos-7.0-64-puppet"
  	centos7.vm.box_version = "1.0.1"
  	centos7.vm.box_check_update = false
  	centos7.vm.network "private_network", ip: "192.168.33.17"
  end

  config.vm.define "CentOS_6_test" do |centos6|
  	centos6.vm.box = "puppetlabs/centos-6.6-64-puppet"
  	centos6.vm.box_version = "1.0.1"
  	centos6.vm.box_check_update = false
  	centos6.vm.network "private_network", ip: "192.168.33.16"
  end

  config.vm.define "Ubuntu_15_test" do |ubuntu|
    ubuntu.vm.box = "ubuntu/wily64"
    ubuntu.vm.box_version = "20160329.0.0"
    ubuntu.vm.box_check_update = false
    ubuntu.vm.network "private_network", ip: "192.168.33.15"
    ubuntu.vm.synced_folder "C:/Users/Alexander/Dropbox/Projects/puppet/keys/", 	"/etc/puppet/hieradata/keys/"
  end

  config.vm.define "Ubuntu_14_test" do |ubuntu_trusty|
    ubuntu_trusty.vm.box = "ubuntu/trusty64"
    ubuntu_trusty.vm.box_check_update = false
    ubuntu_trusty.vm.network "private_network", ip: "192.168.33.14"
    ubuntu_trusty.vm.synced_folder "C:/Users/Alexander/Dropbox/Projects/puppet/keys/", 	"/etc/puppet/hieradata/keys/"
  end

end
