# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.

  config.ssh.insert_key = false
  config.vm.define "dev" do |dev|
    dev.vm.hostname = "jenkins-dev"
    dev.vm.network "private_network", ip: "192.168.33.16"
    dev.vm.box = "ubuntu/wily64"
  	dev.vm.synced_folder "../", "/etc/puppet/modules"
    dev.vm.synced_folder "~/Dropbox/Projects/Jenkins", "/vagrant/backups/"
	  dev.vm.provision "puppet" do |puppet|
 		  puppet.manifests_path = "manifests"
		  puppet.manifest_file  = "jenkins.pp"
    end
    dev.vm.provider "virtualbox" do |v|
      v.memory = 2048
    end
  end

  config.vm.define "prod" do |prod|
    prod.vm.hostname = "jenkins-prod"
    prod.vm.network "private_network", ip: "192.168.4.5"
    prod.vm.box = "ubuntu/wily64"
  end

  config.vm.define "CentOS_7_test" do |centos7|
  	centos7.vm.box = "puppetlabs/centos-7.0-64-puppet"
  	centos7.vm.box_version = "1.0.1"
  	centos7.vm.box_check_update = false
  end

  config.vm.define "CentOS_6_test" do |centos6|
  	centos6.vm.box = "puppetlabs/centos-6.6-64-puppet"
  	centos6.vm.box_version = "1.0.1"
  	centos6.vm.box_check_update = false
  end

  config.vm.define "Ubuntu_15_test" do |ubuntu|
    ubuntu.vm.box = "ubuntu/wily64"
    ubuntu.vm.box_check_update = false
  end

end
