# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "base"
  config.vm.box_check_update = false

  # config.vm.network "forwarded_port", guest: 80, host: 8080
  # config.vm.network "private_network", ip: "192.168.33.10"
  # config.vm.network "public_network"

  # config.vm.synced_folder "../data", "/vagrant_data"

  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end

  config.ssh.insert_key = false
  config.vm.synced_folder "../", "/etc/puppet/modules"

  config.vm.define "CentOS_6_test" do |centos6|
    centos6.vm.box = "puppetlabs/centos-6.6-64-puppet"
    centos6.vm.network "private_network", ip: "192.168.33.26"
    centos6.vm.box_version = "1.0.1"
    centos6.vm.hostname = "ddclient.centos6.vm"
  end

  config.vm.define "CentOS_7_test" do |centos7|
    centos7.vm.box = "puppetlabs/centos-7.0-64-puppet"
    centos7.vm.network "private_network", ip: "192.168.33.27"
    centos7.vm.box_version = "1.0.1"
    centos7.vm.hostname = "httpd.centos7.vm"
  end

  config.vm.define "Ubuntu_15_test" do |ubuntu|
    ubuntu.vm.network "private_network", ip: "192.168.33.15"
    ubuntu.vm.box = "ubuntu/wily64"
    ubuntu.vm.box_check_update = false
  end

  config.vm.define "Ubuntu_16_test" do |ubuntu|
    ubuntu.ssh.private_key_path = "~/.vagrant.d/20170926_vagrant_private_key"
    ubuntu.vm.network "private_network", ip: "192.168.33.16"
    ubuntu.vm.box = "reclusive/xenial64-puppet"
    ubuntu.vm.box_check_update = true
    ubuntu.vm.synced_folder "../../support-scripts/", 	"/usr/local/bin/"
  end

  config.vm.define "Ubuntu_18_test" do |ubuntu|
    # Puppet 5 requires the following command to work
    # sudo puppet apply --modulepath=/etc/puppet/modules /vagrant/manifests/init.pp
    ubuntu.ssh.private_key_path = "~/.vagrant.d/20170926_vagrant_private_key"
    ubuntu.vm.network "private_network", ip: "192.168.33.18"
    ubuntu.vm.box = "reclusive/bionic64-puppet"
    ubuntu.vm.box_check_update = true
    ubuntu.vm.synced_folder "../../support-scripts/", 	"/usr/local/bin/"
  end
end
