# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"
  
	#How to set the hostname on this machine?
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	# All Vagrant configuration is done here. The most common configuration
	# options are documented and commented below. For a complete reference,
	# please see the online documentation at vagrantup.com.

	# Every Vagrant virtual environment requires a box to build off of.
	config.vm.box = "puppetlabs/centos-6.6-64-puppet"
	config.vm.box_check_update = false

	#Master configuration
	config.vm.define "master" do |master|
  		# Create a private network, which allows host-only access to the machine
  		# using a specific IP.
		master.vm.network "private_network", ip: "192.168.33.10"
		
		# Share an additional folder to the guest VM. The first argument is
		# the path on the host to the actual folder. The second argument is
		# the path on the guest to mount the folder. And the optional third
		# argument is a set of non-required options.
		master.vm.synced_folder "manifests", "/puppet_data"
		master.vm.synced_folder "configuration", "/configuration_files"
		master.vm.synced_folder "installers", "/installers"
		master.vm.synced_folder "../modules",	"/etc/puppet/modules"

		# Enable provisioning with Puppet stand alone.  Puppet manifests
		# are contained in a directory path relative to this Vagrantfile.
		# You will need to create the manifests directory and a manifest in
		# the file default.pp in the manifests_path directory.

		master.vm.provision "puppet" do |puppet|
 			# puppet.options 			= ["--fileserverconfig=/vagrant/fileserver.conf"] #--verbose --debug 
			puppet.manifests_path 	= "manifests"
			puppet.manifest_file  	= "init.pp"
			#   puppet.module_path		= "../modules/mysql"
		end		
		#End Puppet provisioning
	end		
	#End master definition
  
	#Agent node definition
	config.vm.define "agent" do |agent|
  		agent.vm.network "private_network", ip: "192.168.33.11"
  		agent.vm.synced_folder "manifests", "/puppet_data"
  		agent.vm.provision "puppet" do |puppet|
  			# puppet.options 			= ["--fileserverconfig=/vagrant/fileserver.conf"] #--verbose --debug 
    		puppet.manifests_path 	= "manifests"
    		puppet.manifest_file  	= "site.pp"
  		end		
  		#End puppet provisioning
	end		
	#End Agent definition
  
end
