# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|  
#  config.vm.box = "puppetlabs/centos-6.6-64-puppet"
  config.vm.box = "puppetlabs/centos-7.0-64-puppet"
  config.vm.box_check_update = false
  config.vm.box_version = "1.0.1"
  config.vm.hostname = "php.vm"
  # config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "private_network", ip: "192.168.33.12", auto_config: true

  config.vm.synced_folder "../", 	"/etc/puppet/modules"
    
  # config.vm.provision "puppet" do |puppet|
  # 	puppet.manifests_path = "manifests"
  # 	puppet.manifest_file  = "init.pp"
  # 	puppet.options = ["--templatedir","/tmp/vagrant-puppet-3/templates"]
  # end

  config.vm.define "CentOS_7_test" do |centos7|
  	centos7.vm.box = "puppetlabs/centos-7.0-64-puppet"
  	centos7.vm.box_version = "1.0.1"
  	centos7.vm.box_check_update = false
  end

  config.vm.define "CentOS_6_test" do |centos6|
  	centos6.vm.box = "puppetlabs/centos-6.6-64-puppet"
  	centos6.vm.box_version = "1.0.1"
  	centos6.vm.box_check_update = false
  end

  config.vm.define "Ubuntu_15_test" do |ubuntu|
    ubuntu.vm.box = "ubuntu/wily64"
    ubuntu.vm.box_check_update = false
  end

end
