# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "puppetlabs/centos-6.6-64-puppet"
  config.vm.box_version = "1.0.1"
  config.vm.box_check_update = false

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  	config.vm.synced_folder "../",	"/etc/puppet/modules"
  	
#  config.vm.provision "puppet" do |puppet|
#     puppet.manifests_path = "manifests"
#     puppet.manifest_file  = "init.pp"
#  end

  config.vm.define "centos7" do |centos7|
  	centos7.vm.box = "puppetlabs/centos-7.0-64-puppet"
  	centos7.vm.box_version = "1.0.1"
  	centos7.vm.box_check_update = false
  end

  config.vm.define "centos6" do |centos6|
  	centos6.vm.box = "puppetlabs/centos-6.6-64-puppet"
  	centos6.vm.box_version = "1.0.1"
  	centos6.vm.box_check_update = false
  end
end
