# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
    # The most common configuration options are documented and commented below.
    # For a complete reference, please see the online documentation at
    # https://docs.vagrantup.com.

    config.vm.box_check_update = false
    config.ssh.insert_key = false
    config.vm.synced_folder "../", "/etc/puppet/modules/"
    #Getting the error:Cannot allocate memory - fork(2)
	#Ruby needs more headroom to fork processes as it copies the entire parent context before collapsing it down.
  	config.vm.provider "virtualbox" do |vb|
    	vb.memory = "1024"
	end

    # Every Vagrant virtual environment requires a box to build off of.
    config.vm.define "CentOS_6_test" do |centos|
        centos.vm.hostname = "maven-dev-centos6"
  	    centos.vm.box = "puppetlabs/centos-6.6-64-puppet"
        centos.vm.box_version = "1.0.1"
        centos.vm.network "private_network", ip: "192.168.33.16"
    end

    config.vm.define "CentOS_7_test" do |centos|
        centos.vm.hostname = "maven-dev-centos7"
        centos.vm.box = "puppetlabs/centos-7.0-64-puppet"
        centos.vm.box_version = "1.0.1"
        centos.vm.network "private_network", ip: "192.168.33.17"
    end

    config.vm.define "Ubuntu_15_test" do |ubuntu|
        ubuntu.vm.hostname = "maven-dev-ubuntu"
        ubuntu.vm.network "private_network", ip: "192.168.33.17"
#        ubuntu.vm.network "private_network", ip: "192.168.33.15"
#        ubuntu.vm.box = "ubuntu/trusty64"
        ubuntu.vm.box = "ubuntu/wily64"
        ubuntu.vm.box_version = "20160329.0.0"
    end
    config.vm.define "Ubuntu_16_test" do |ubuntu|
        ubuntu.vm.box_check_update = true
        ubuntu.ssh.private_key_path = "~/.vagrant.d/20170926_vagrant_private_key"
        ubuntu.vm.box = "reclusive/xenial64-puppet"
        ubuntu.vm.network "private_network", ip: "192.168.33.26"
        ubuntu.vm.hostname = "maven.ubuntu.vm"
    end
end
