#!/bin/bash  
# description: Puppet master Start Stop Restart  
# processname: puppet master
# chkconfig: 234 20 80  
# I suspect that the chkconfig configuration to be erroneous
  
PATH=/usr/bin:/sbin:/bin:/usr/sbin
export PATH
 
#Load global variables from file
#[ -f /etc/sysconfig/puppet ] && . /etc/sysconfig/puppet
puppetd=${PUPPETD-/usr/bin/puppet}
#pidopts=${} 
RETVAL=0

# Source function library.
. /etc/rc.d/init.d/functions

PUPPET_OPTS="master "

function getPid() {
	echo `ps aux | grep 'puppet master' | grep -v 'grep' | awk '{ print $2 }'`
}

case $1 in  
start)
	echo -n $"Starting puppet master: "
	/usr/bin/puppet master
	echo "Pid $(getPid)"
;;

stop)
	echo "Stopping puppet master $(getPid):"
#	killproc $puppetd
	if [ -n $(getPid) ]; then
		echo "Trying to kill pid $(getPid)"
		kill -9 $(getPid)
	fi
	if [ -z $(getPid) ]; then
		echo "Puppet master successfully killed"
	fi		
;;

restart)
	echo "Restarting puppet master $(getPid): "
#	killproc $puppetd -HUP
	if [ -n $(getPid) ]; then
		echo "Trying to kill pid $(getPid)"
		kill -9 $(getPid)
	fi
	if [ -z $(getPid) ]; then
		echo "Puppet master successfully killed"
	fi	
	echo -n $"Starting puppet master: "
	/usr/bin/puppet master
	echo "Pid $(getPid)"
;;

  
status)
	echo -n $"Puppet master status:"
	status $puppetd
;;
   
esac      
exit 0  
 