# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.

  
	config.vm.box_check_update = false
	config.ssh.insert_key = false
	config.vm.network "forwarded_port", guest: 8080, host: 8100
	config.vm.network "private_network", ip: "192.168.33.10", auto_config: true
  	config.vm.synced_folder "../", 	"/etc/puppet/modules"
    config.vm.synced_folder "templates", "/tmp/vagrant-puppet-3/templates"
  	
	config.vm.provision "puppet" do |puppet|
  		puppet.manifests_path = "manifests"
  		puppet.manifest_file  = "init.pp"
  		puppet.options = ["--templatedir","/tmp/vagrant-puppet-3/templates"]
	end


  # Enable provisioning with Puppet stand alone.  Puppet manifests
  # are contained in a directory path relative to this Vagrantfile.
  # You will need to create the manifests directory and a manifest in
  # the file default.pp in the manifests_path directory.
  #
#   config.vm.provision "puppet" do |puppet|
#   	puppet.manifests_path = "manifests"
#   	puppet.manifest_file  = "init.pp"
#  	puppet.options = ["--templatedir","/tmp/vagrant-puppet-3/templates"]
#   end

  config.vm.define "centos6_test" do |centos6_test|
    centos6_test.vm.box = "puppetlabs/centos-6.6-64-puppet"
    centos6_test.vm.box_version = "1.0.1"
  end
	config.vm.define "ubuntu" do |ubuntu|
	  	ubuntu.vm.box = "ubuntu/wily64"
	  	ubuntu.vm.hostname = "tomcat-dev-ubuntu"
	end
	
	config.vm.define "centos6" do |centos6|
  		centos6.vm.box = "puppetlabs/centos-6.6-64-puppet"
  		centos6.vm.hostname = "tomcat-dev-centos6"
	end
	
end
