# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  config.vm.box_check_update = false
  config.vm.synced_folder "../", 	"/etc/puppet/modules"
  config.ssh.insert_key = false

  # Enable provisioning with Puppet stand alone.  Puppet manifests
  # are contained in a directory path relative to this Vagrantfile.
  # You will need to create the manifests directory and a manifest in
  # the file default.pp in the manifests_path directory.
  #
#	config.vm.provision "puppet" do |puppet|
#		puppet.manifests_path = "manifests"
#	 	puppet.manifest_file  = "init.pp"
#  		puppet.options = ["--templatedir","/tmp/vagrant-puppet-3/templates"]
#	end
		
  config.vm.define "CentOS_7_test" do |centos7|
  	centos7.vm.box = "puppetlabs/centos-7.0-64-puppet"
  	centos7.vm.box_version = "1.0.1"
  	centos7.vm.box_check_update = false
  	centos7.vm.network "private_network", ip: "192.168.33.17"
  end

  config.vm.define "CentOS_6_test" do |centos6|
  	centos6.vm.box = "puppetlabs/centos-6.6-64-puppet"
  	centos6.vm.box_version = "1.0.1"
  	centos6.vm.box_check_update = false
  	centos6.vm.network "private_network", ip: "192.168.33.16"
  end

  config.vm.define "Ubuntu_15_test" do |ubuntu|
    ubuntu.vm.box = "ubuntu/wily64"
    ubuntu.vm.box_check_update = false
    ubuntu.vm.network "private_network", ip: "192.168.33.15"
    ubuntu.vm.synced_folder "files/keys/", 	"/etc/puppet/hieradata/keys/"
  end

  config.vm.define "Ubuntu_18_test" do |ubuntu|
    ubuntu.vm.box_check_update = true
    ubuntu.ssh.private_key_path = "~/.vagrant.d/20170926_vagrant_private_key"
    ubuntu.vm.box = "reclusive/bionic64-puppet"
    ubuntu.vm.network "private_network", ip: "192.168.33.28"
    ubuntu.vm.hostname = "jenkins.ubuntu.vm"
    ubuntu.vm.box_version = "0.0.2020-12-01-0200"
    ubuntu.vm.synced_folder "../../support-scripts/", 	"/usr/local/bin/"
    ubuntu.vm.synced_folder "C:/Users/Alexander/Dropbox/Projects/puppet/keys/", 	"/etc/puppet/hieradata/keys/"
    #ubuntu.vm.synced_folder "files/keys/", 	"/etc/puppet/hieradata/keys/"
  end
end
