# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "base"
  config.vm.box_check_update = false

  # config.vm.synced_folder "../data", "/vagrant_data"

  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end

  config.vm.synced_folder "../", "/etc/puppet/modules"
  config.vm.define "Ubuntu_18_test" do |ubuntu|
    # Puppet 5 requires the following command to work
    # sudo puppet apply --modulepath=/etc/puppet/modules /vagrant/tests/certbot.pp
    ubuntu.ssh.private_key_path = "~/.vagrant.d/20170926_vagrant_private_key"
    ubuntu.vm.network "private_network", ip: "192.168.33.18"
    ubuntu.vm.box = "reclusive/bionic64-puppet"
    ubuntu.vm.box_check_update = true
    ubuntu.vm.synced_folder "../../support-scripts/", 	"/usr/local/bin/"
    ubuntu.vm.synced_folder "../", "/etc/puppet/modules"
  end
end
