# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

    config.vm.box_check_update = false
    config.ssh.insert_key = false
	config.vm.synced_folder "../", "/etc/puppet/modules/"
	#Getting the error:Cannot allocate memory - fork(2)
	#Ruby needs more headroom to fork processes as it copies the entire parent context before collapsing it down.
  	config.vm.provider "virtualbox" do |vb|
    	vb.memory = "1024"
	end
  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.define "centos" do |centos|
    centos.vm.hostname = "java-dev-centos"
  	centos.vm.box = "puppetlabs/centos-6.6-64-puppet"
	centos.vm.box_version = "1.0.1"
    centos.vm.network "private_network", ip: "192.168.33.10"
    
#	centos.vm.provision "puppet" do |puppet|
# 		puppet.manifests_path = "manifests"
#		puppet.manifest_file  = "test_centos.pp"
#	end
  end


  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.hostname = "java-dev-ubuntu"
    ubuntu.vm.network "private_network", ip: "192.168.33.15"
    ubuntu.vm.box = "ubuntu/wily64"
	ubuntu.vm.synced_folder "files", "/vagrant/debs"
		
#	ubuntu.vm.provision "puppet" do |puppet|
# 		puppet.manifests_path = "manifests"
#		puppet.manifest_file  = "test_ubuntu.pp"
#	end
  end
  
end
