name    'Alexander-master_agent'
version '0.1.0'
source ''
author ''
license ''
summary 'Example of a master agent setup using vagrant'
description ''
project_page ''

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
