# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
#  	config.vm.box = "puppetlabs/centos-6.6-64-puppet"
 	config.vm.box = "puppetlabs/centos-7.0-64-puppet"
  	config.vm.box_check_update = true
  	config.ssh.insert_key = false
  	config.vm.box_version = "1.0.1"
    config.vm.hostname = "kanboard.vm"
	config.vm.synced_folder "../", 	"/etc/puppet/modules"
	config.vm.synced_folder "templates", "/tmp/vagrant-puppet-3/templates"
    
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end
#  config.vm.provision "puppet" do |puppet|
#  	puppet.manifests_path = "tests"
#  	puppet.manifest_file  = "kanboard.pp"
#  	puppet.options = ["--templatedir","/tmp/vagrant-puppet-3/templates"]
#  end
  
  config.vm.define "server" do |server|
    server.vm.network "public_network", :mac => "080027D3418E", :bridge => "Realtek PCIe GBE Family Controller"
	server.vm.synced_folder "/home/alexander/Dropbox/Projects/kanboard/backup", "/vagrant/backups" 
  end

  config.vm.define "laptopserver" do |laptopserver|
    laptopserver.vm.network "public_network", :mac => "080027D3418E", :bridge => "Realtek PCIe GBE Family Controller"
	laptopserver.vm.synced_folder "D:/Dropbox/Projects/kanboard/backup", "/vagrant/backups" 
  end


  config.vm.define "local" do |local|
    local.vm.network "private_network", ip: "192.168.33.35"
	local.vm.synced_folder "C:/Users/Alexander/Dropbox/Projects/kanboard/backup/test/", "/vagrant/backups" 
  end
  
    config.vm.define "CentOS_7_test" do |centos7|
    	centos7.vm.box = "puppetlabs/centos-7.0-64-puppet"
    	centos7.vm.box_version = "1.0.1"
    	centos7.vm.box_check_update = false
      centos7.vm.network "private_network", ip: "192.168.33.17"
    end
  
    config.vm.define "CentOS_6_test" do |centos6|
    	centos6.vm.box = "puppetlabs/centos-6.6-64-puppet"
    	centos6.vm.box_version = "1.0.1"
    	centos6.vm.box_check_update = false
      centos6.vm.network "private_network", ip: "192.168.33.16"
    end
  
    config.vm.define "Ubuntu_15_test" do |ubuntu|
      ubuntu.vm.box = "ubuntu/wily64"
      ubuntu.vm.box_version = "20160315.0.0"
      ubuntu.vm.box_check_update = false
      ubuntu.vm.network "private_network", ip: "192.168.33.15"
    end   
end
