# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  	config.vm.box = "puppetlabs/centos-6.6-64-puppet"
  	config.vm.box_check_update = true
  	config.vm.box_version = "1.0.1"
    config.vm.network "public_network", :mac => "080027D3418E", :bridge => "Realtek PCIe GBE Family Controller"
    # Mask:255.255.255.0
     
#   config.vm.network "public_network", ip: "192.168.33.10", auto_config: true #auto_config prevents us setting the correct interface as a bridged adapter
#   config.vm.network "forwarded_port", guest: 80, host: 8080
#    config.vm.network "private_network", ip: "192.168.33.10", auto_config: true
    config.vm.hostname = "kanboard.vm"
    
  # config.vm.synced_folder "../data", "/vagrant_data"
#	config.vm.synced_folder ".", 	"/var/www"
	config.vm.synced_folder "../", 	"/etc/puppet/modules"
	config.vm.synced_folder "templates", "/tmp/vagrant-puppet-3/templates"
	config.vm.synced_folder "C:/Users/Alexander/Dropbox/Projects/kanboard/backup", "/vagrant/backups" 

# 	config.vm.provision :shell, :path => "files/install.sh"    
  # Enable provisioning with Puppet stand alone.  Puppet manifests
  # are contained in a directory path relative to this Vagrantfile.
  # You will need to create the manifests directory and a manifest in
  # the file default.pp in the manifests_path directory.

  config.vm.provision "puppet" do |puppet|
  	puppet.manifests_path = "manifests"
  	puppet.manifest_file  = "kanboard.pp"
  	puppet.options = ["--templatedir","/tmp/vagrant-puppet-3/templates"]
  end
  
  
  config.vm.define "server" do |server|
	server.vm.synced_folder "D:/Dropbox/Projects/kanboard/backup", "/vagrant/backups" 
  end
end
