# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

#  config.vm.box_version = "1.0.1"
  config.vm.box_check_update = false
  config.ssh.insert_key = false

  config.vm.synced_folder "../", 	"/etc/puppet/modules"
#	config.vm.synced_folder "templates",
	 
  # Enable provisioning with Puppet stand alone.  Puppet manifests
  # are contained in a directory path relative to this Vagrantfile.
  # You will need to create the manifests directory and a manifest in
  # the file default.pp in the manifests_path directory.
  
  config.vm.define "server" do | server |
	server.vm.box = "puppetlabs/centos-6.6-64-puppet"
#	server.vm.network "public_network", :mac => "080027D3418F", :bridge => "Realtek PCIe GBE Family Controller"
	server.vm.provision "puppet" do |puppet|
		puppet.manifests_path = "manifests"
		puppet.manifest_file  = "jekyll.pp"
#    	puppet.options = ["--templatesdir","/tmp/vagrant-puppet-3/template"]
	end
  end

  config.vm.define "ubuntu" do | ubuntu |
	ubuntu.vm.box = "ubuntu/wily64"
	ubuntu.vm.box_version = "20160329.0.0"
	ubuntu.vm.hostname = "dev.jekyll"
	
	ubuntu.vm.network "private_network", ip: "192.168.33.25"
	ubuntu.vm.network "forwarded_port", guest: "4000", host: "8888"
	
	ubuntu.vm.synced_folder "C:\\Git Checkouts\\ahopgood.github.io", "/blog"
	ubuntu.vm.synced_folder "published_blog", "/published_blog"
	
	ubuntu.vm.synced_folder "../", "/etc/puppet/modules"
	ubuntu.vm.provision "puppet" do |puppet|
		puppet.manifests_path = "manifests"
		puppet.manifest_file  = "jekyll.pp"
	end

  end 
  
      config.vm.define "CentOS_7_test" do |centos7|
      	centos7.vm.box = "puppetlabs/centos-7.0-64-puppet"
      	centos7.vm.box_version = "1.0.1"
      	centos7.vm.box_check_update = false
      end
    
      config.vm.define "CentOS_6_test" do |centos6|
      	centos6.vm.box = "puppetlabs/centos-6.6-64-puppet"
      	centos6.vm.box_version = "1.0.1"
      	centos6.vm.box_check_update = false
      end
    
      config.vm.define "Ubuntu_15_test" do |ubuntu|
        ubuntu.vm.box = "ubuntu/wily64"
        ubuntu.vm.box_check_update = false
      end

    config.vm.define "Ubuntu_18_test" do |ubuntu|
        ubuntu.vm.box_check_update = true
        ubuntu.ssh.private_key_path = "~/.vagrant.d/20170926_vagrant_private_key"
        ubuntu.vm.box = "reclusive/bionic64-puppet"
        #ubuntu.vm.box_version = "0.0.2020-05-06-0100"
        ubuntu.vm.network "private_network", ip: "192.168.33.28"
        ubuntu.vm.hostname = "ubuntu-18"
        ubuntu.vm.synced_folder "../../support-scripts/", 	"/usr/local/bin/support/"
        ubuntu.vm.synced_folder "C:\\Git Checkouts\\ahopgood.github.io", "/blog"
        ubuntu.vm.synced_folder "published_blog", "/published_blog"

        ubuntu.vm.provision "shell", inline: <<-SHELL
            echo "Running shell provisioner"
            sudo puppet apply --modulepath=/etc/puppet/modules/ /vagrant/manifests/jekyll.pp
        SHELL
    end

    config.vm.define "blog-test" do |ubuntu|
        ubuntu.vm.box_check_update = false
        ubuntu.ssh.private_key_path = "~/.vagrant.d/20170926_vagrant_private_key"
        ubuntu.vm.box = "reclusive/jekyll4"
        ubuntu.vm.network "private_network", ip: "192.168.33.28"
        ubuntu.vm.hostname = "ubuntu-18"
#        ubuntu.vm.synced_folder "../../support-scripts/", 	"/usr/local/bin/"
        ubuntu.vm.synced_folder "C:\\Git Checkouts\\ahopgood.github.io", "/blog"
        ubuntu.vm.synced_folder "published_blog", "/published_blog"
    end
end
